// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vogel.MediaEngine.Infrastructure.EntityFramework;

#nullable disable

namespace Vogel.MediaEngine.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(MediaEngineDbContext))]
    partial class MediaEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MediaEngine")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vogel.MediaEngine.Domain.Medias.Media", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime?>("DeletionTime")
                    .HasColumnType("datetime2");

                b.Property<string>("DeletorId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("File")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("MimeType")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<int>("MediaType")
                    .HasColumnType("int");

                b.Property<long>("Size")
                    .HasColumnType("bigint");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("CreatorId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreationTime")
                    .HasColumnType("datetime2");

                b.Property<string>("ModifierId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ModificationTime")
                    .HasColumnType("datetime2");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Medias", "MediaEngine");
            });
#pragma warning restore 612, 618
        }
    }
}
